name: Update Windrun Banner

on:
  schedule:
    - cron: '0 */3 * * *'  # каждые 3 часа (UTC)
  workflow_dispatch:       # позволяет запускать вручную

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          go run main.go
